## Examples 1 and 2 of week 3 

The simplest way to look at the value of a tensor is to return that tensor to a numpy array. Once we have the tensor
as a numpy array we can explore its values and properties

In [1]:
# load the libraries we'll need
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import sys
np.set_printoptions(suppress=True)

### Working with eager mode

In [3]:
# create random input data
x_input = np.random.uniform(size=(1,10)).astype(np.float32)
W = tf.Variable(tf.random.uniform([10,2]),name='W')
b = tf.Variable(tf.ones([2]),name='b')

In [4]:
# perform a simple operation
def multiply_add(x):
    return tf.matmul(x,W) + b

In [5]:
# make the calculation
y = multiply_add(x_input)

In [6]:
print(x_input)

[[0.7992789  0.09258717 0.35380244 0.224984   0.809047   0.7323675
  0.0970499  0.85807866 0.07256071 0.9258714 ]]


In [7]:
# print the variables and the result of the calculation
print(b.numpy())

[1. 1.]


In [8]:
print(W.numpy())

[[0.37257445 0.94718444]
 [0.20778668 0.10490167]
 [0.19372952 0.18732738]
 [0.38599277 0.6380019 ]
 [0.22425842 0.79848886]
 [0.73025846 0.19685745]
 [0.5713742  0.96111155]
 [0.9068489  0.53334165]
 [0.02731204 0.27493   ]
 [0.69286    0.8929341 ]]


In [9]:
print(y.numpy())

[[3.6657474 4.1643972]]


### Using graph node

#### First, we’ll use eager mode again to make a slightly different calculation

In [10]:
# create a new variable
b_init = tf.Variable(tf.ones([2]),name='b_init')

# perform the operation in a loop
def multiply_add(x,b):
    for i in range(5):
        output = tf.matmul(x,W) + b
        # increase the value of b
        b = tf.add(output, b)
        # here we print the offset b which will change values within the loop
        print(b)
    return output

In [11]:
# run the function that will execute the for-loop
y = multiply_add(x_input,b_init)

tf.Tensor([[4.6657476 5.1643972]], shape=(1, 2), dtype=float32)
tf.Tensor([[11.997243 13.493192]], shape=(1, 2), dtype=float32)
tf.Tensor([[26.660233 30.15078 ]], shape=(1, 2), dtype=float32)
tf.Tensor([[55.986214 63.465958]], shape=(1, 2), dtype=float32)
tf.Tensor([[114.638176 130.09631 ]], shape=(1, 2), dtype=float32)


### Next, we’ll convert to graph mode by introducing a function decorator

In [13]:
@tf.function
def multiply_add(x,b):
    for i in range(5):
        output = tf.matmul(x,W) + b
        # increase the value of b
        b = tf.add(output, b)
        # here we print the offset b which will change values within the loop
        print(b)
    return output

In [14]:
# run the function that will execute the for-loop
y = multiply_add(x_input,b_init)

Tensor("Add_1:0", shape=(1, 2), dtype=float32)
Tensor("Add_3:0", shape=(1, 2), dtype=float32)
Tensor("Add_5:0", shape=(1, 2), dtype=float32)
Tensor("Add_7:0", shape=(1, 2), dtype=float32)
Tensor("Add_9:0", shape=(1, 2), dtype=float32)


In [ ]:
# The value of the tensor is not displayed !
# This is because in graph mode the sequence of operations is constructed so that they can be re-used with
# different inputs

In [15]:
# Plus if we call the function again, we can see that nothing is printed.
# The print statement is executed only when the graph is compiled, and this happens only once
# when the function is called first
y = multiply_add(x_input,b_init)