In [3]:
import tensorflow as tf
import numpy as np

In [4]:
#First we’ll create a tensor to hold the text,
hello = tf.constant('Hello world!')

In [5]:
#Lets see what happens when we print this tensor
print(hello)
## tf.Tensor(b'Hello world!', shape=(), dtype=string)
# What we see here is both the text that is contained in the constant hello and some of its properties, its
# shape and data type.

tf.Tensor(b'Hello world!', shape=(), dtype=string)


Next we’ll do some calculations. First, we’ll create two tensors that have a constant value then add them
together

In [9]:
# create a constant with value 5
x = tf.constant(5.0)
# create a constant with value 15
y = tf.constant(15.0)
# add the two constants together and print
z = x + y
print(z)

#alternative 
#z = tf.add(x,y)

tf.Tensor(20.0, shape=(), dtype=float32)


In [7]:
#We can repeat this exercise with rank-2 tensors now.
# create constant tensors
x = tf.constant([[1, 2, 3],[4, 5, 6]])
y = tf.constant([[6, 5, 4],[3, 2, 1]])
# add them together and print
z = tf.add(x,y)
print(z)

tf.Tensor(
[[7 7 7]
 [7 7 7]], shape=(2, 3), dtype=int32)


We now introduce
Tensorflow variables that contain values that can change during the course of program execution.

In [10]:
x = tf.Variable(2, tf.int16)
y = tf.Variable(3, tf.int16)
z = tf.Variable(2, tf.int16)
# perform operations on the variables
xy = tf.add(x, y)
xyz = tf.multiply(xy, z)
print(xyz)

tf.Tensor(10, shape=(), dtype=int32)


In [11]:
# print the original variable
print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>


In [12]:
# update its value
x.assign(3, read_value=False)
# print the new variable
print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


In [13]:
# repeat the calculations
xy = tf.add(x, y)
xyz = tf.multiply(xy, z)
print(xyz)

tf.Tensor(12, shape=(), dtype=int32)


We can replace the TensorFlow variable declaration in our earlier example with standard python variables.
create variables

In [14]:
x = 2
y = 3
z = 2
#perform operations on the variables
xy = tf.add(x, y)
xyz = tf.multiply(xy, z)
# print the output
print(xyz)

#Here the operation tf.add has taken in normal variables, converted them to tensors and then performed
#the operations

tf.Tensor(10, shape=(), dtype=int32)


In [15]:
# create variables
x = 2
y = 3
z = 2
#perform operations on the variables
xy = tf.add(x, y)
xyz = tf.multiply(xy, z)
# print the output
print(xyz)

#Here the operation tf.add has taken in normal variables, converted them to tensors and then performed
#the operations

tf.Tensor(10, shape=(), dtype=int32)


In [19]:
# create some numpy arrays with all the same values
x = np.full((3,3),2)
y = np.full((3,3),3)
z = np.full((3,3),2)
#perform operations on the variables
xy = tf.add(x, y)
xyz = tf.multiply(xy, z)

In [20]:
print(xy)

tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int64)


In [22]:
print(xyz)

tf.Tensor(
[[10 10 10]
 [10 10 10]
 [10 10 10]], shape=(3, 3), dtype=int64)


In [25]:
#and if we want to specifically access the result as an array in numpy, we can execute the following,
# store the numpy array in a new variable
xyz_np = xyz.numpy()
# print the array
print(xyz_np)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [27]:
#Example of error
x = np.full((3,2),2)
y = np.full((3,3),3)
z = np.full((3,3),2)
xy = tf.add(x, y)
xyz = tf.multiply(xy, z)

2023-05-07 10:22:42.155851: W tensorflow/core/framework/op_kernel.cc:1733] INVALID_ARGUMENT: required broadcastable shapes


InvalidArgumentError: required broadcastable shapes [Op:AddV2]